const COFFEE_NOTE_GROUPS: Record<string, string[]> = {
  감귤: ["감귤", "감귤류"],
  다크초콜릿: [
    "다크 초콜렛",
    "다크 초콜릿",
    "다크초코",
    "다크초콜렛",
    "Dark Chocolate",
    "Dark chocolate",
  ],
  밀크초콜릿: ["밀크초콜렛", "밀크 초콜릿", "Milk Chocolate", "Milk chocolate"],
  플로럴: [
    "꽃향",
    "꽃향기",
    "플로럴",
    "은은한 꽃",
    "Flower tea",
    "Floral",
    "White floral",
  ],
  초콜릿: ["초콜렛", "초콜릿", "Chocolate"],
  자스민: [
    "자스민",
    "자스민 허브",
    "재스민",
    "말린 재스민",
    "Jasmine",
    "향수같은 재스민",
  ],
  꿀: ["꿀", "허니", "Honey&Caramel", "Honey"],
  샤인머스캣: ["샤인머스캣", "샤인머스켓", "Shine Musket"],
  오렌지: [
    "오렌지",
    "오렌지 주스",
    "오렌지블라썸",
    "Orange peel",
    "Orange Peel",
  ],
  와인: [
    "와인",
    "와이니",
    "Red Wine",
    "White Wine",
    "Winey",
    "Port Wine",
    "화이트와인",
    "Wine",
  ],
  카라멜: ["카라멜", "카라멜 시럽", "캬라멜", "Caramel"],
  견과류: [
    "견과류",
    "너트류",
    "땅콩",
    "볶은 견과류",
    "아몬드",
    "Almond",
    "캐슈넛",
    "피넛",
    "Cashew Nut",
    "Cashewnut",
    "Roasted Almond",
    "Roasted Chestnut",
    "Roasted nut",
    "Walnuts",
    "Macadamia",
    "Nut Chocolate",
    "Pecan",
  ],
  체리: ["체리", "Cherry", "Cherry candy"],
  다크체리: ["다크체리", "다크 체리", "Black Cherry"],
  베리: ["베리", "베리계열의 향미", "Berry jam"],
  브라운슈가: ["브라운슈가", "브라운 슈가", "슈가브라운", "Brown Sugar"],
  블랙베리: ["블랙베리", "블랙 베리", "Blackberry"],
  홍차: ["홍차", "블랙티", "Black Tea", "Black tea", "Blacktea"],
  포도: [
    "포도",
    "청포도",
    "적포도",
    "백포도",
    "Campbell Grape",
    "Grape",
    "Grapefruit",
    "White Grape",
    "Red Grape",
  ],
  사과: [
    "사과",
    "빨간 사과",
    "풋사과",
    "apple",
    "Apple",
    "Green Apple",
    "Green apple",
  ],
  아카시아: ["아카시아", "Acacia Honey"],
  살구: ["살구", "Apricot"],
  베르가못: ["베르가못", "Bergamot"],
  균형잡힌산미: ["균형잡힌산미", "Balanced", "Well Balanced", "Well-balance"],
  블랙커런트: ["블랙커런트", "Black currant"],
  블러드오렌지: ["블러드오렌지", "Blood Orange"],
  블루베리: ["블루베리", "Blueberry"],
  깔끔함: [
    "깔끔함",
    "깨끗한 뒷맛",
    "Bright Acidity",
    "Clean",
    "Clean Aftertaste",
    "Very Clean",
  ],
  풍선껌: ["풍선껌", "Bubble gum"],
  카카오: ["카카오", "Cacao"],
  카카오닙스: ["카카오닙스", "Cacao Nibs", "Cacaonips"],
  카모마일: ["카모마일", "Chamomile"],
  부드러움: ["부드러움", "Creamy Body", "Creamy", "Soft Body", "Smooth"],
  부드러운산미: ["부드러운산미", "Soft Acidity"],
  시트러스: ["시트러스", "Citrus"],
  크랜베리: ["크랜베리", "Cranberry"],
  레몬: ["레몬", "Lemon Candy", "Lemon Tea", "Lemon tea"],
  레몬그라스: ["레몬그라스", "Lemongrass"],
  얼그레이: ["얼그레이", "earl grey"],
  열대과일: ["열대과일", "Tropical fruit", "Tropical Fruit"],
  라즈베리: [
    "라즈베리",
    "Raspberry",
    "Raspberry Jam",
    "Raspberry Chocolate",
    "Respberry",
  ],
  허브: ["허브", "Herbal", "Herby", "다양한 허브", "Minty"],
  히비스커스: ["히비스커스", "Hibiscus"],
  헤이즐넛: ["헤이즐넛", "Hazelnut"],
  말린과일: ["말린과일", "Dried Fruit"],
  무화과: ["무화과", "Fig"],
  자두: ["자두", "plum", "Plum", "Plum Juice", "Dried Plum"],
  시럽: [
    "시럽",
    "Maple syrup",
    "Maple Syrup",
    "Maple",
    "Syrupy",
    "Syrupy body",
    "Syrupy texture",
  ],
  바닐라: ["바닐라", "Vanilla"],
  복숭아: ["복숭아", "Peach", "yellow peach"],
  당밀: ["당밀", "Toffee", "Molasses"],
  딸기: ["딸기", "Strawberry"],
  장미: ["장미", "Rose", "Rose floral"],
  단맛: ["단맛", "Sweet"],
  탠저린: ["탠저린", "Tangerine"],
  호박: ["호박", "Sweet Pumkin"],
  멜론: ["멜론", "Melon"],
  쥬시: ["쥬시", "Juicy", "과즙"],
  파인애플: ["파인애플", "Pineapple"],
  건포도: ["건포도", "raisin", "Raisin", "Dried grapefruit"],
  사탕수수: ["사탕수수", "Sugar cane", "Sugarcane"],
  로즈마리: ["로즈마리", "Rosemary"],
  스톤프룻: ["스톤프룻", "Stonefruit", "Red Fruit Stone Fruit"],
  풍부한바디감: ["풍부한바디감", "Full-body", "풍부한 바디감"],
  긴여운: ["긴여운", "Long Aftertaste", "Lingering", "Long after", "긴 여운"],
  리치: ["리치", "Lychee"],
  망고: ["망고", "Mango", "애플망고"],
  라임: ["라임", "Lime"],
  석류: ["석류", "Pomegranate"],
};

function transformObject(
  input: Record<string, string[]>
): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [key, values] of Object.entries(input)) {
    for (const value of values) {
      result[value] = key;
    }
  }

  return result;
}

export const COFFEE_NOTE_DICT = transformObject(COFFEE_NOTE_GROUPS);

export const getSegmentedNote = (notes: string[]) =>
  notes.map((note) => COFFEE_NOTE_DICT[note] ?? note);
